services:
  api:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: actuarial-api

    environment:
      MSSQL_SA_PASSWORD: "${MSSQL_SA_PASSWORD}"
      MSSQL_SERVER: "sqlserver"

    ports:
      - "8000:8000"

    volumes:
      - .:/app

    depends_on:
      - sqlserver

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    platform: linux/amd64

    container_name: actuarial-sqlserver

    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "${MSSQL_SA_PASSWORD}"
      MSSQL_PID: "Developer"

    ports:
      - "1433:1433"

    volumes:
      - sqlserver_data:/var/opt/mssql

volumes:
  sqlserver_data: